package org.home.demo.x001.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResponseObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String responseCD;
	private String responseMsg;

	public ResponseObject() {
	}

	public String getResponseCD() {
		return this.responseCD;
	}

	public void setResponseCD(String responseCD) {
		this.responseCD = responseCD;
	}

	public String getResponseMsg() {
		return this.responseMsg;
	}

	public void setResponseMsg(String responseMsg) {
		this.responseMsg = responseMsg;
	}

	public ResponseObject(String responseCD,
                          String responseMsg) {
		this.responseCD = responseCD;
		this.responseMsg = responseMsg;
	}

}