package org.home.demo.x001.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestDataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String test;

	private String test_field1;

	private Integer test_field2;

	private java.time.LocalDate test_field3;

	public TestDataObject() {
	}

	public String getTest() {
		return this.test;
	}

	public void setTest(String test) {
		this.test = test;
	}

	public String getTest_field1() {
		return this.test_field1;
	}

	public void setTest_field1(String test_field1) {
		this.test_field1 = test_field1;
	}

	public Integer getTest_field2() {
		return this.test_field2;
	}

	public void setTest_field2(Integer test_field2) {
		this.test_field2 = test_field2;
	}

	public java.time.LocalDate getTest_field3() {
		return this.test_field3;
	}

	public void setTest_field3(java.time.LocalDate test_field3) {
		this.test_field3 = test_field3;
	}

	public TestDataObject(String test, String test_field1,
                          Integer test_field2, java.time.LocalDate test_field3) {
		this.test = test;
		this.test_field1 = test_field1;
		this.test_field2 = test_field2;
		this.test_field3 = test_field3;
	}

}