package org.home.demo.x001;

import org.home.demo.x001.models.TestDataObject;
dialect "mvel";

// rule values at B10, header at B5
rule "TestFieldsTable Sheet_10"
	when
		testObjectAlias : TestDataObject(test_field1 == "X1");
	then
		testObjectAlias.setTest_field3( "Test 1 was true" );
end

//rule "TestFieldsTable Hello_10"
//	when
//        testObjectAlias:TestDataObject(test_field1 == "X1");
//	then
//        testObjectAlias.setTest_field3("Test 1 was true");
//end